---
- name: Set up LeanStore environment and compile
  hosts: client-0
  become: yes
  vars:
    java_home: /usr/lib/jvm/java-17-openjdk-amd64
    local_leanstore_dir: /home/nati/Desktop/DMLAB/temp/leanstore #/path/to/your/local/leanstore  # Update this
    remote_leanstore_dir: /opt/leanstore

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - cmake
          - libtbb2-dev
          - libaio-dev
          - libsnappy-dev
          - zlib1g-dev
          - libbz2-dev
          - liblz4-dev
          - libzstd-dev
          - librocksdb-dev
          - liblmdb-dev
          - libwiredtiger-dev
          - liburing-dev
          - openjdk-17-jdk
          - maven
          - clang-14
          - rsync
        state: present

    - name: Set JAVA_HOME
      lineinfile:
        path: /etc/environment
        line: "JAVA_HOME={{ java_home }}"

    - name: Set CXX to clang++-14
      lineinfile:
        path: /etc/environment
        line: "CXX=clang++-14"

    - name: Create LeanStore directory
      file:
        path: "{{ remote_leanstore_dir }}"
        state: directory

    - name: Synchronize LeanStore files from local to remote
      synchronize:
        src: "{{ local_leanstore_dir }}/"
        dest: "{{ remote_leanstore_dir }}"
        delete: yes
        recursive: yes
        rsync_opts:
          - "--exclude=.git"
      delegate_to: localhost

    - name: Ensure correct permissions
      file:
        path: "{{ remote_leanstore_dir }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes

    - name: Compile Java wrapper and LeanStore
      shell: |
        source /etc/environment
        cd {{ remote_leanstore_dir }}/bookkeeper-helper && mvn package
        cd {{ remote_leanstore_dir }} && mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
        make tpcc
      environment:
        JAVA_HOME: "{{ java_home }}"
        CXX: clang++-14

    - name: Create leanstore file
      file:
        path: "{{ remote_leanstore_dir }}/leanstore"
        state: touch

    - name: Set execute permissions for tpcc binary
      file:
        path: "{{ remote_leanstore_dir }}/build/frontend/tpcc"
        mode: u+x,g+x,o+x

    - name: Print completion message
      debug:
        msg: "LeanStore has been set up, compiled, and the TPC-C benchmark is ready to run."