services:
  zookeeper:
    image: zookeeper:latest
    restart: always
    networks:
      - bookkeeper-internal
    ports:
      - 2181:2181/tcp
  bookie-01:
    image: apache/bookkeeper:latest
    restart: always
    networks:
      - bookkeeper-internal
    ports:
      - 3181:3181/tcp
      - 8081:8080/tcp
    links:
      - zookeeper
    depends_on:
      - zookeeper
    volumes:
      - ./bookkeeper-conf/bk_server.conf:/opt/bookkeeper/conf/bk_server.conf:ro
    environment:
      BK_zkServers: zookeeper:2181
  bookie-02:
    image: apache/bookkeeper:latest
    restart: always
    networks:
      - bookkeeper-internal
    ports:
      - 3182:3181/tcp
      - 8082:8080/tcp
    links:
      - zookeeper
    depends_on:
      - zookeeper
    volumes:
      - ./bookkeeper-conf/bk_server.conf:/opt/bookkeeper/conf/bk_server.conf:ro
    environment:
      BK_zkServers: zookeeper:2181
  bookie-03:
    image: apache/bookkeeper:latest
    restart: always
    networks:
      - bookkeeper-internal
    ports:
      - 3183:3181/tcp
      - 8083:8080/tcp
    links:
      - zookeeper
    depends_on:
      - zookeeper
    volumes:
      - ./bookkeeper-conf/bk_server.conf:/opt/bookkeeper/conf/bk_server.conf:ro
    environment:
      BK_zkServers: zookeeper:2181

networks:
  bookkeeper-internal:
